language: python
python:
- '2.7'
before_install:
- openssl aes-256-cbc -K $encrypted_6ee4f911b84d_key -iv $encrypted_6ee4f911b84d_iv -in travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- sudo apt-get update
install:
- sudo apt-get -y install lzop curl
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
# needed especially for fake_jumpstart
- sudo pip install docopt
before_script:
- cp travis/id_rsa.pub ~/.ssh/id_rsa.pub
- cat travis/id_rsa.pub > ~/.ssh/authorized_keys
- pyinstaller -F -n server jsc/server.py
- cp dist/server /tmp/server
- sudo cp travis/fake_jumpstart.py /bin/jumpstart
- sudo chmod +x /bin/jumpstart
script:
  python -m unittest jsc.tests.test_travis
before_deploy:
- fab ul_server
deploy:
  provider: testpypi
  user: jumpstarter
  password:
    secure: O9jLN4UcBrJwDjGpwaABsDYnrt4wbyV3vqK5aXzELpi+Nygswx3X7H+WtN1AXVWuSlFuI0XswLEntG3/CpRAn6EQmisRXofKqaybXaa7QqbUcrkpjhez6X/8qFl3T18OVmpBKiu3FUXXH2Dwlr8KrewBe2cF9W5Ub26UR1hvIRs=
  on:
    tags: true
    branch: master
notifications:
  hipchat:
    rooms:
      secure: DWQjs1nvskIoIdWSOknIZyZbLSOpEONju3VcFpKEV86+bWXhPc0E9dCXGEWYwemwHStsQf8/gpoINSUqiNFptvtM+0t8lvZiRZgIuqALajE073CecZexrh/PyTSM7kWc5aZH3WTmVd2LohUvASHvSoG6Xs6fvCbj2NpIsm4TZxQ=
  email: false
