language: python
python:
- '2.7'
before_install:
  openssl aes-256-cbc -K $encrypted_6ee4f911b84d_key -iv $encrypted_6ee4f911b84d_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
before_script:
- cp id_rsa.pub ~/.ssh/id_rsa.pub
- cat id_rsa.pub > ~/.ssh/authorized_keys
- pyinstaller -F -n server jsc/server.py
- cp dist/server /tmp/server
script:
- python setup.py test
before_deploy:
- fab ul_server
deploy:
  provider: testpypi
  user: jumpstarter
  password:
    secure: O9jLN4UcBrJwDjGpwaABsDYnrt4wbyV3vqK5aXzELpi+Nygswx3X7H+WtN1AXVWuSlFuI0XswLEntG3/CpRAn6EQmisRXofKqaybXaa7QqbUcrkpjhez6X/8qFl3T18OVmpBKiu3FUXXH2Dwlr8KrewBe2cF9W5Ub26UR1hvIRs=
  on:
    tags: true
    branch: master
notifications:
  hipchat:
    rooms:
      secure: l3H9fiRVsIXlKrAgDlQUSpZrLVSG8h4FFro9EfdhcqucAXHSc3K7i7pl1AXmQww/885UlvE5lA9GyqjV92y/vMumn6MPWYlS8BgCum5bPwKsHnu6oe6krzZDrEBNLwcA97M9R32cmayPos+yR780hDp1x7h+UGStAZMyohOGif0=
  email: false
